# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: o-postgress
    shm_size: 128mb
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: user
      POSTGRES_DB: otus
    ports:
     - "5432:5432"

  adminer:
    image: adminer
    container_name: o-adminer
    ports:
      - 8080:8080
